yaml
name: Android CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # 만약 실패하면 이 부분을 '11' 또는 '21'로 변경해 보세요
        distribution: 'temurin'
        cache: gradle

    - name: Change wrapper permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
